title: "Ortzi Garaio Portfolio"

author: "Ortzi"
email: "Ortzi@egmail.com"

theme: jekyll-theme-minimal

github_username: ortzigaraio


logo: foto_perfil_cv.png   # si subes una foto a esa ruta
# Configuraci√≥n opcional
show_downloads: false




